var color_name=["red","blue","pink","brown","yellow","cyan","white","purple","green"]
var score=0;
var timeleft=20;
document.getElementById("a").disabled=true;
document.getElementById("start").disabled=false;
document.getElementById("b").disabled=true;
document.getElementById("c").disabled=true;
document.getElementById("d").disabled=true;
document.getElementById("e").disabled=true;
document.getElementById("f").disabled=true;
document.getElementById("g").disabled=true;
document.getElementById("h").disabled=true;
document.getElementById("i").disabled=true;

function timer()
{
document.getElementById("timer").innerHTML=timeleft;
document.getElementById("score").innerHTML=score;
document.getElementById("start").disabled=true;
document.getElementById("a").disabled=false;
document.getElementById("b").disabled=false;
document.getElementById("c").disabled=false;
document.getElementById("d").disabled=false;
document.getElementById("e").disabled=false;
document.getElementById("f").disabled=false;
document.getElementById("g").disabled=false;
document.getElementById("h").disabled=false;
document.getElementById("i").disabled=false;
    var timer=setInterval(function(){
timeleft--;
    document.getElementById("timer").innerHTML=timeleft;
    if(timeleft==0)
        {   clearInterval(timer);
            alert("GAME OVER!! Your score is " + score)
            timeleft=20;
            score=0;
document.getElementById("a").disabled=true;
document.getElementById("start").disabled=false;
document.getElementById("b").disabled=true;
document.getElementById("c").disabled=true;
document.getElementById("d").disabled=true;
document.getElementById("e").disabled=true;
document.getElementById("f").disabled=true;
document.getElementById("g").disabled=true;
document.getElementById("h").disabled=true;
document.getElementById("i").disabled=true;
        }
    },1000)
}
function color()
{
var a=Math.floor(Math.random()*9)+1;
    switch(a)
        {
                case 1:
                document.getElementById("color_name").innerHTML=color_name[0];
                document.getElementById("color0").innerHTML=color_name[4];
                document.getElementById("a").style.background=color_name[2];
                document.getElementById("color1").innerHTML=color_name[5];
                document.getElementById("b").style.background=color_name[1];
                document.getElementById("color2").innerHTML=color_name[6];
                document.getElementById("c").style.background=color_name[4];
                document.getElementById("color3").innerHTML=color_name[2];
                document.getElementById("d").style.background=color_name[0];
                document.getElementById("color4").innerHTML=color_name[3];
                document.getElementById("e").style.background=color_name[5];
                document.getElementById("color5").innerHTML=color_name[3];
                document.getElementById("f").style.background=color_name[6];
                document.getElementById("color6").innerHTML=color_name[0];
                document.getElementById("g").style.background=color_name[3];
                document.getElementById("color7").innerHTML=color_name[6];
                document.getElementById("h").style.background=color_name[8];
                document.getElementById("color8").innerHTML=color_name[8];
                document.getElementById("i").style.background=color_name[7];
                break;
                case 2:
                document.getElementById("color_name").innerHTML=color_name[1];
                document.getElementById("color0").innerHTML=color_name[4];
                document.getElementById("a").style.background=color_name[6];
                document.getElementById("color1").innerHTML=color_name[6];
                document.getElementById("b").style.background=color_name[4];
                document.getElementById("color2").innerHTML=color_name[3];
                document.getElementById("c").style.background=color_name[3];
                document.getElementById("color3").innerHTML=color_name[1];
                document.getElementById("d").style.background=color_name[1];
                document.getElementById("color4").innerHTML=color_name[7];
                document.getElementById("e").style.background=color_name[2];
                document.getElementById("color5").innerHTML=color_name[4];
                document.getElementById("f").style.background=color_name[5];
                document.getElementById("color6").innerHTML=color_name[5];
                document.getElementById("g").style.background=color_name[7];
                document.getElementById("color7").innerHTML=color_name[3];
                document.getElementById("h").style.background=color_name[8];
                document.getElementById("color8").innerHTML=color_name[8];
                document.getElementById("i").style.background=color_name[0];
                break;
                case 3:
                document.getElementById("color_name").innerHTML=color_name[2];
                document.getElementById("color0").innerHTML=color_name[3];
                document.getElementById("a").style.background=color_name[1];
                document.getElementById("color1").innerHTML=color_name[7];
                document.getElementById("b").style.background=color_name[2];
                document.getElementById("color2").innerHTML=color_name[1];
                document.getElementById("c").style.background=color_name[6];
                document.getElementById("color3").innerHTML=color_name[6];
                document.getElementById("d").style.background=color_name[5];
                document.getElementById("color4").innerHTML=color_name[2];
                document.getElementById("e").style.background=color_name[3];
                document.getElementById("color5").innerHTML=color_name[4];
                document.getElementById("f").style.background=color_name[0];
                document.getElementById("color6").innerHTML=color_name[3];
                document.getElementById("g").style.background=color_name[4];
                document.getElementById("color7").innerHTML=color_name[5];
                document.getElementById("h").style.background=color_name[8];
                document.getElementById("color8").innerHTML=color_name[8];
                document.getElementById("i").style.background=color_name[7];
                break;
                case 4:
                document.getElementById("color_name").innerHTML=color_name[3];
                document.getElementById("color0").innerHTML=color_name[5];
                document.getElementById("a").style.background=color_name[4];
                document.getElementById("color1").innerHTML=color_name[1];
                document.getElementById("b").style.background=color_name[2];
                document.getElementById("color2").innerHTML=color_name[6];
                document.getElementById("c").style.background=color_name[1];
                document.getElementById("color3").innerHTML=color_name[3];
                document.getElementById("d").style.background=color_name[0];
                document.getElementById("color4").innerHTML=color_name[6];
                document.getElementById("e").style.background=color_name[8];
                document.getElementById("color5").innerHTML=color_name[7];
                document.getElementById("f").style.background=color_name[3];
                document.getElementById("color6").innerHTML=color_name[3];
                document.getElementById("g").style.background=color_name[6];
                document.getElementById("color7").innerHTML=color_name[0];
                document.getElementById("h").style.background=color_name[5];
                document.getElementById("color8").innerHTML=color_name[2];
                document.getElementById("i").style.background=color_name[7];
                break;
                case 5:
                document.getElementById("color_name").innerHTML=color_name[4];
                document.getElementById("color0").innerHTML=color_name[3];
                document.getElementById("a").style.background=color_name[0];
                document.getElementById("color1").innerHTML=color_name[5];
                document.getElementById("b").style.background=color_name[1];
                document.getElementById("color2").innerHTML=color_name[6];
                document.getElementById("c").style.background=color_name[5];
                document.getElementById("color3").innerHTML=color_name[7];
                document.getElementById("d").style.background=color_name[2];
                document.getElementById("color4").innerHTML=color_name[1];
                document.getElementById("e").style.background=color_name[7];
                document.getElementById("color5").innerHTML=color_name[8];
                document.getElementById("f").style.background=color_name[4];
                document.getElementById("color6").innerHTML=color_name[4];
                document.getElementById("g").style.background=color_name[8];
                document.getElementById("color7").innerHTML=color_name[0];
                document.getElementById("h").style.background=color_name[3];
                document.getElementById("color8").innerHTML=color_name[1];
                document.getElementById("i").style.background=color_name[6];
                break;
                case 6:
                document.getElementById("color_name").innerHTML=color_name[5];
                document.getElementById("color0").innerHTML=color_name[2];
                document.getElementById("a").style.background=color_name[1];
                document.getElementById("color1").innerHTML=color_name[1];
                document.getElementById("b").style.background=color_name[0];
                document.getElementById("color2").innerHTML=color_name[6];
                document.getElementById("c").style.background=color_name[8];
                document.getElementById("color3").innerHTML=color_name[4];
                document.getElementById("d").style.background=color_name[2];
                document.getElementById("color4").innerHTML=color_name[7];
                document.getElementById("e").style.background=color_name[5];
                document.getElementById("color5").innerHTML=color_name[5];
                document.getElementById("f").style.background=color_name[7];
                document.getElementById("color6").innerHTML=color_name[0];
                document.getElementById("g").style.background=color_name[6];
                document.getElementById("color7").innerHTML=color_name[1];
                document.getElementById("h").style.background=color_name[4];
                document.getElementById("color8").innerHTML=color_name[8];
                document.getElementById("i").style.background=color_name[3];
                break;
                case 7:
                document.getElementById("color_name").innerHTML=color_name[6];
                document.getElementById("color0").innerHTML=color_name[5];
                document.getElementById("a").style.background=color_name[3];
                document.getElementById("color1").innerHTML=color_name[4];
                document.getElementById("b").style.background=color_name[2];
                document.getElementById("color2").innerHTML=color_name[8];
                document.getElementById("c").style.background=color_name[6];
                document.getElementById("color3").innerHTML=color_name[1];
                document.getElementById("d").style.background=color_name[4];
                document.getElementById("color4").innerHTML=color_name[6];
                document.getElementById("e").style.background=color_name[8];
                document.getElementById("color5").innerHTML=color_name[0];
                document.getElementById("f").style.background=color_name[1];
                document.getElementById("color6").innerHTML=color_name[3];
                document.getElementById("g").style.background=color_name[0];
                document.getElementById("color7").innerHTML=color_name[4];
                document.getElementById("h").style.background=color_name[5];
                document.getElementById("color8").innerHTML=color_name[8];
                document.getElementById("i").style.background=color_name[7];
                break;
                case 8:
                document.getElementById("color_name").innerHTML=color_name[7];
                document.getElementById("color0").innerHTML=color_name[1];
                document.getElementById("a").style.background=color_name[7];
                document.getElementById("color1").innerHTML=color_name[8];
                document.getElementById("b").style.background=color_name[1];
                document.getElementById("color2").innerHTML=color_name[2];
                document.getElementById("c").style.background=color_name[5];
                document.getElementById("color3").innerHTML=color_name[0];
                document.getElementById("d").style.background=color_name[4];
                document.getElementById("color4").innerHTML=color_name[3];
                document.getElementById("e").style.background=color_name[2];
                document.getElementById("color5").innerHTML=color_name[7];
                document.getElementById("f").style.background=color_name[0];
                document.getElementById("color6").innerHTML=color_name[4];
                document.getElementById("g").style.background=color_name[3];
                document.getElementById("color7").innerHTML=color_name[6];
                document.getElementById("h").style.background=color_name[8];
                document.getElementById("color8").innerHTML=color_name[5];
                document.getElementById("i").style.background=color_name[6];
                break;
                case 9:
                document.getElementById("color_name").innerHTML=color_name[8];
                document.getElementById("color0").innerHTML=color_name[2];
                document.getElementById("a").style.background=color_name[6];
                document.getElementById("color1").innerHTML=color_name[5];
                document.getElementById("b").style.background=color_name[4];
                document.getElementById("color2").innerHTML=color_name[7];
                document.getElementById("c").style.background=color_name[2];
                document.getElementById("color3").innerHTML=color_name[6];
                document.getElementById("d").style.background=color_name[8];
                document.getElementById("color4").innerHTML=color_name[1];
                document.getElementById("e").style.background=color_name[5];
                document.getElementById("color5").innerHTML=color_name[4];
                document.getElementById("f").style.background=color_name[3];
                document.getElementById("color6").innerHTML=color_name[8];
                document.getElementById("g").style.background=color_name[0];
                document.getElementById("color7").innerHTML=color_name[0];
                document.getElementById("h").style.background=color_name[7];
                document.getElementById("color8").innerHTML=color_name[2];
                document.getElementById("i").style.background=color_name[1];
                break;
        }
}
function compare(x)
{
    var z=x;
    var y=document.getElementById("color_name").innerHTML;
    if(y==z)
        {
            ++score;
            document.getElementById("score").innerHTML=score;
            document.getElementById("body").style.background="green";
        }
    else
        {
            document.getElementById("body").style.background="red";
        }
    color();
}