var color_name=["red","blue","pink","brown","yellow","cyan","white","purple","green"]
var t=25;
function timer()
{   document.getElementById("timer").innerHTML=t;
    t--;
 if(t==-1)
     {
         window.alert("Game over");
         t=25;
     }
}
function color()
{
var a=Math.floor(Math.random()*9)+1;
    switch(a)
        {
                case 1:
                document.getElementById("color_name").innerHTML=color_name[0];
                document.getElementById("color0").innerHTML=color_name[4];
                document.getElementById("a").style.background=color_name[2];
                document.getElementById("color1").innerHTML=color_name[5];
                document.getElementById("b").style.background=color_name[1];
                document.getElementById("color2").innerHTML=color_name[6];
                document.getElementById("c").style.background=color_name[4];
                document.getElementById("color3").innerHTML=color_name[2];
                document.getElementById("d").style.background=color_name[0];
                document.getElementById("color4").innerHTML=color_name[3];
                document.getElementById("e").style.background=color_name[5];
                document.getElementById("color5").innerHTML=color_name[3];
                document.getElementById("f").style.background=color_name[6];
                document.getElementById("color6").innerHTML=color_name[0];
                document.getElementById("g").style.background=color_name[3];
                document.getElementById("color7").innerHTML=color_name[6];
                document.getElementById("h").style.background=color_name[8];
                document.getElementById("color8").innerHTML=color_name[8];
                document.getElementById("i").style.background=color_name[7];
                break;
                case 2:
                document.getElementById("color_name").innerHTML=color_name[1];
                document.getElementById("color0").innerHTML=color_name[4];
                document.getElementById("a").style.background=color_name[6];
                document.getElementById("color1").innerHTML=color_name[6];
                document.getElementById("b").style.background=color_name[4];
                document.getElementById("color2").innerHTML=color_name[3];
                document.getElementById("c").style.background=color_name[3];
                document.getElementById("color3").innerHTML=color_name[1];
                document.getElementById("d").style.background=color_name[1];
                document.getElementById("color4").innerHTML=color_name[7];
                document.getElementById("e").style.background=color_name[2];
                document.getElementById("color5").innerHTML=color_name[4];
                document.getElementById("f").style.background=color_name[5];
                document.getElementById("color6").innerHTML=color_name[5];
                document.getElementById("g").style.background=color_name[7];
                document.getElementById("color7").innerHTML=color_name[3];
                document.getElementById("h").style.background=color_name[8];
                document.getElementById("color8").innerHTML=color_name[8];
                document.getElementById("i").style.background=color_name[0];
                break;
                case 3:
                document.getElementById("color_name").innerHTML=color_name[2];
                document.getElementById("color0").innerHTML=color_name[3];
                document.getElementById("a").style.background=color_name[1];
                document.getElementById("color1").innerHTML=color_name[7];
                document.getElementById("b").style.background=color_name[2];
                document.getElementById("color2").innerHTML=color_name[1];
                document.getElementById("c").style.background=color_name[6];
                document.getElementById("color3").innerHTML=color_name[6];
                document.getElementById("d").style.background=color_name[5];
                document.getElementById("color4").innerHTML=color_name[2];
                document.getElementById("e").style.background=color_name[3];
                document.getElementById("color5").innerHTML=color_name[4];
                document.getElementById("f").style.background=color_name[0];
                document.getElementById("color6").innerHTML=color_name[3];
                document.getElementById("g").style.background=color_name[4];
                document.getElementById("color7").innerHTML=color_name[5];
                document.getElementById("h").style.background=color_name[8];
                document.getElementById("color8").innerHTML=color_name[8];
                document.getElementById("i").style.background=color_name[7];
                break;
                case 4:
                document.getElementById("color_name").innerHTML=color_name[3];
                document.getElementById("color0").innerHTML=color_name[5];
                document.getElementById("a").style.background=color_name[4];
                document.getElementById("color1").innerHTML=color_name[1];
                document.getElementById("b").style.background=color_name[2];
                document.getElementById("color2").innerHTML=color_name[6];
                document.getElementById("c").style.background=color_name[1];
                document.getElementById("color3").innerHTML=color_name[3];
                document.getElementById("d").style.background=color_name[0];
                document.getElementById("color4").innerHTML=color_name[6];
                document.getElementById("e").style.background=color_name[8];
                document.getElementById("color5").innerHTML=color_name[7];
                document.getElementById("f").style.background=color_name[3];
                document.getElementById("color6").innerHTML=color_name[3];
                document.getElementById("g").style.background=color_name[6];
                document.getElementById("color7").innerHTML=color_name[0];
                document.getElementById("h").style.background=color_name[5];
                document.getElementById("color8").innerHTML=color_name[2];
                document.getElementById("i").style.background=color_name[7];
                break;
                case 5:
                document.getElementById("color_name").innerHTML=color_name[4];
                document.getElementById("color0").innerHTML=color_name[3];
                document.getElementById("a").style.background=color_name[0];
                document.getElementById("color1").innerHTML=color_name[5];
                document.getElementById("b").style.background=color_name[1];
                document.getElementById("color2").innerHTML=color_name[6];
                document.getElementById("c").style.background=color_name[5];
                document.getElementById("color3").innerHTML=color_name[7];
                document.getElementById("d").style.background=color_name[2];
                document.getElementById("color4").innerHTML=color_name[1];
                document.getElementById("e").style.background=color_name[7];
                document.getElementById("color5").innerHTML=color_name[8];
                document.getElementById("f").style.background=color_name[4];
                document.getElementById("color6").innerHTML=color_name[4];
                document.getElementById("g").style.background=color_name[8];
                document.getElementById("color7").innerHTML=color_name[0];
                document.getElementById("h").style.background=color_name[3];
                document.getElementById("color8").innerHTML=color_name[1];
                document.getElementById("i").style.background=color_name[6];
                break;
                case 6:
                document.getElementById("color_name").innerHTML=color_name[5];
                document.getElementById("color0").innerHTML=color_name[2];
                document.getElementById("a").style.background=color_name[1];
                document.getElementById("color1").innerHTML=color_name[1];
                document.getElementById("b").style.background=color_name[0];
                document.getElementById("color2").innerHTML=color_name[6];
                document.getElementById("c").style.background=color_name[8];
                document.getElementById("color3").innerHTML=color_name[4];
                document.getElementById("d").style.background=color_name[2];
                document.getElementById("color4").innerHTML=color_name[7];
                document.getElementById("e").style.background=color_name[5];
                document.getElementById("color5").innerHTML=color_name[5];
                document.getElementById("f").style.background=color_name[7];
                document.getElementById("color6").innerHTML=color_name[0];
                document.getElementById("g").style.background=color_name[6];
                document.getElementById("color7").innerHTML=color_name[1];
                document.getElementById("h").style.background=color_name[4];
                document.getElementById("color8").innerHTML=color_name[8];
                document.getElementById("i").style.background=color_name[3];
                break;
                case 7:
                document.getElementById("color_name").innerHTML=color_name[6];
                document.getElementById("color0").innerHTML=color_name[5];
                document.getElementById("a").style.background=color_name[3];
                document.getElementById("color1").innerHTML=color_name[4];
                document.getElementById("b").style.background=color_name[2];
                document.getElementById("color2").innerHTML=color_name[8];
                document.getElementById("c").style.background=color_name[6];
                document.getElementById("color3").innerHTML=color_name[1];
                document.getElementById("d").style.background=color_name[4];
                document.getElementById("color4").innerHTML=color_name[6];
                document.getElementById("e").style.background=color_name[8];
                document.getElementById("color5").innerHTML=color_name[0];
                document.getElementById("f").style.background=color_name[1];
                document.getElementById("color6").innerHTML=color_name[3];
                document.getElementById("g").style.background=color_name[0];
                document.getElementById("color7").innerHTML=color_name[4];
                document.getElementById("h").style.background=color_name[5];
                document.getElementById("color8").innerHTML=color_name[8];
                document.getElementById("i").style.background=color_name[7];
                break;
                case 8:
                document.getElementById("color_name").innerHTML=color_name[7];
                document.getElementById("color0").innerHTML=color_name[1];
                document.getElementById("a").style.background=color_name[7];
                document.getElementById("color1").innerHTML=color_name[8];
                document.getElementById("b").style.background=color_name[1];
                document.getElementById("color2").innerHTML=color_name[2];
                document.getElementById("c").style.background=color_name[5];
                document.getElementById("color3").innerHTML=color_name[0];
                document.getElementById("d").style.background=color_name[4];
                document.getElementById("color4").innerHTML=color_name[3];
                document.getElementById("e").style.background=color_name[2];
                document.getElementById("color5").innerHTML=color_name[7];
                document.getElementById("f").style.background=color_name[0];
                document.getElementById("color6").innerHTML=color_name[4];
                document.getElementById("g").style.background=color_name[3];
                document.getElementById("color7").innerHTML=color_name[6];
                document.getElementById("h").style.background=color_name[8];
                document.getElementById("color8").innerHTML=color_name[5];
                document.getElementById("i").style.background=color_name[6];
                break;
                case 9:
                document.getElementById("color_name").innerHTML=color_name[8];
                document.getElementById("color0").innerHTML=color_name[2];
                document.getElementById("a").style.background=color_name[6];
                document.getElementById("color1").innerHTML=color_name[5];
                document.getElementById("b").style.background=color_name[4];
                document.getElementById("color2").innerHTML=color_name[7];
                document.getElementById("c").style.background=color_name[2];
                document.getElementById("color3").innerHTML=color_name[6];
                document.getElementById("d").style.background=color_name[8];
                document.getElementById("color4").innerHTML=color_name[1];
                document.getElementById("e").style.background=color_name[5];
                document.getElementById("color5").innerHTML=color_name[4];
                document.getElementById("f").style.background=color_name[3];
                document.getElementById("color6").innerHTML=color_name[8];
                document.getElementById("g").style.background=color_name[0];
                document.getElementById("color7").innerHTML=color_name[0];
                document.getElementById("h").style.background=color_name[7];
                document.getElementById("color8").innerHTML=color_name[2];
                document.getElementById("i").style.background=color_name[1];
                break;
        }
}